name: Test Docker Build

on:
  workflow_dispatch:

#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  bockerize_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: prabhushan
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: prabhushan/test-service:${{ github.ref_name }}-${{ github.sha }}
          
    - name: COPY CONTAINER IMAGE NAME
      run: echo "CONTAINER IMAGE:" ${{ github.ref_name }}-${{ github.sha }}
